
export enum UserRole {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER'
}

export enum AdminStatus {
  PENDING = 'Pending',
  ACCEPTED = 'Accepted',
  REJECTED = 'Rejected' // Or just deleted
}

export enum OrderStatus {
  PREPARING = 'جاري التحضير',
  ON_WAY = 'في الطريق',
  DELIVERED = 'تم التسليم'
}

export enum ProductCategory {
  MEAT = 'اللحوم',
  FRUITS_VEG = 'الفواكه والخضار',
  CAKE = 'الكيك',
  BISCUITS = 'البسكويت',
  JUICES = 'العصائر',
  DRINKS = 'المشروبات الغازية / الطاقة',
  CLEANING = 'منتجات التنظيف',
  PERSONAL_CARE = 'منتجات العناية الشخصية'
}

export interface User {
  id: string;
  name: string;
  email?: string; // Optional for customers if just using localStorage ID
  password?: string;
  role: UserRole;
  status?: AdminStatus; // Only for admins
  phone?: string;
  location?: string; // Simplified for demo
}

export interface Product {
  id: string;
  name: string;
  category: ProductCategory;
  price: number;
  stock: number;
  discount?: number; // Percentage
  imageUrl: string;
  description?: string; // Generated by Gemini
  isOffer?: boolean;
}

export interface CartItem extends Product {
  quantity: number;
}

export interface Order {
  id: string;
  userId: string;
  customerName: string;
  customerPhone: string;
  customerLocation: string;
  items: CartItem[];
  total: number;
  status: OrderStatus;
  date: string;
}

export interface Notification {
  id: string;
  message: string;
  date: string;
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'bot';
  text: string;
  suggestedProduct?: Product;
}

export const COLORS = {
  ORANGE: '#F68B1F',
  GREEN: '#0C612D',
  WHITE: '#FFFFFF',
  GRAY_LIGHT: '#F3F4F6',
  RED: '#EF4444'
};
